/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;


import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.security.autoconfigure.UserDetailsServiceAutoConfiguration;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.ComponentScan;
import org.springframework.context.annotation.EnableAspectJAutoProxy;
import org.springframework.data.jpa.repository.config.EnableJpaRepositories;


@SpringBootApplication()
@EnableJpaRepositories(basePackages = {"org.example.repository"})
@ComponentScan(basePackages = {"org.example"})
public class App {
// This is commit check

    public static void main(String[] args) {
        SpringApplication.run(App.class, args);
    }

}
